"""auto update

Revision ID: b1f0ca7c0c08
Revises: ffefefadbc84
Create Date: 2026-07-25 00:27:17.058018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f0ca7c0c08'
down_revision: Union[str, Sequence[str], None] = 'ffefefadbc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=True),
    sa.Column('reference_id', sa.String(), server_default='', nullable=True),
    sa.Column('idempotency_key', sa.String(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_id'), 'credit_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_reference_id'), 'credit_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_workspace_id'), 'credit_ledger', ['workspace_id'], unique=False)
    op.create_table('offer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('services', sa.String(), server_default='[]', nullable=True),
    sa.Column('platforms', sa.String(), server_default='[]', nullable=True),
    sa.Column('price_range_min', sa.Integer(), server_default='0', nullable=True),
    sa.Column('price_range_max', sa.Integer(), server_default='0', nullable=True),
    sa.Column('target_categories', sa.String(), server_default='[]', nullable=True),
    sa.Column('target_geographies', sa.String(), server_default='[]', nullable=True),
    sa.Column('languages', sa.String(), server_default='[]', nullable=True),
    sa.Column('min_client_size', sa.String(), server_default='', nullable=True),
    sa.Column('max_client_size', sa.String(), server_default='', nullable=True),
    sa.Column('monthly_capacity', sa.Integer(), server_default='5', nullable=True),
    sa.Column('preferred_channels', sa.String(), server_default='[]', nullable=True),
    sa.Column('portfolio_tags', sa.String(), server_default='[]', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_profiles_id'), 'offer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_offer_profiles_workspace_id'), 'offer_profiles', ['workspace_id'], unique=False)
    op.create_table('provider_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='disconnected', nullable=True),
    sa.Column('config_json', sa.String(), server_default='{}', nullable=True),
    sa.Column('last_health_check', sa.String(), server_default='', nullable=True),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_connections_id'), 'provider_connections', ['id'], unique=False)
    op.create_index(op.f('ix_provider_connections_workspace_id'), 'provider_connections', ['workspace_id'], unique=False)
    op.create_table('search_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='queued', nullable=True),
    sa.Column('filters_json', sa.String(), server_default='{}', nullable=True),
    sa.Column('credits_estimated', sa.Integer(), server_default='1', nullable=True),
    sa.Column('credits_charged', sa.Integer(), server_default='0', nullable=True),
    sa.Column('results_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('progress_pct', sa.Integer(), server_default='0', nullable=True),
    sa.Column('error_message', sa.String(), server_default='', nullable=True),
    sa.Column('started_at', sa.String(), server_default='', nullable=True),
    sa.Column('completed_at', sa.String(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_jobs_id'), 'search_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_search_jobs_workspace_id'), 'search_jobs', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), server_default='member', nullable=True),
    sa.Column('invited_email', sa.String(), server_default='', nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), server_default='trial', nullable=True),
    sa.Column('trial_ends_at', sa.String(), server_default='', nullable=True),
    sa.Column('stripe_customer_id', sa.String(), server_default='', nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), server_default='', nullable=True),
    sa.Column('subscription_status', sa.String(), server_default='trialing', nullable=True),
    sa.Column('monthly_credits', sa.Integer(), server_default='25', nullable=True),
    sa.Column('credits_used', sa.Integer(), server_default='0', nullable=True),
    sa.Column('credits_reset_at', sa.String(), server_default='', nullable=True),
    sa.Column('max_seats', sa.Integer(), server_default='1', nullable=True),
    sa.Column('settings_json', sa.String(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspaces_stripe_customer_id'), 'workspaces', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_workspaces_stripe_subscription_id'), 'workspaces', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_stripe_subscription_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_stripe_customer_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_search_jobs_workspace_id'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_id'), table_name='search_jobs')
    op.drop_table('search_jobs')
    op.drop_index(op.f('ix_provider_connections_workspace_id'), table_name='provider_connections')
    op.drop_index(op.f('ix_provider_connections_id'), table_name='provider_connections')
    op.drop_table('provider_connections')
    op.drop_index(op.f('ix_offer_profiles_workspace_id'), table_name='offer_profiles')
    op.drop_index(op.f('ix_offer_profiles_id'), table_name='offer_profiles')
    op.drop_table('offer_profiles')
    op.drop_index(op.f('ix_credit_ledger_workspace_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_reference_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    # ### end Alembic commands ###