"""auto update

Revision ID: d72942336bd7
Revises: 
Create Date: 2026-07-24 21:57:05.924853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72942336bd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), server_default='note', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_notes_user_id'), 'lead_notes', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), server_default='', nullable=True),
    sa.Column('website_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('social_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('has_website', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('social_platforms', sa.String(), server_default='[]', nullable=True),
    sa.Column('contact_email', sa.String(), server_default='', nullable=True),
    sa.Column('contact_phone', sa.String(), server_default='', nullable=True),
    sa.Column('pipeline_stage', sa.String(), server_default='new_lead', nullable=True),
    sa.Column('priority', sa.String(), server_default='medium', nullable=True),
    sa.Column('notes_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_contacted', sa.String(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_notes_user_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    # ### end Alembic commands ###