"""auto update

Revision ID: ffefefadbc84
Revises: d72942336bd7
Create Date: 2026-07-24 23:13:38.870815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffefefadbc84'
down_revision: Union[str, Sequence[str], None] = 'd72942336bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interaction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('input_summary', sa.String(), nullable=True),
    sa.Column('output_summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interaction_logs_id'), 'ai_interaction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_logs_lead_id'), 'ai_interaction_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_logs_user_id'), 'ai_interaction_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interaction_logs_user_id'), table_name='ai_interaction_logs')
    op.drop_index(op.f('ix_ai_interaction_logs_lead_id'), table_name='ai_interaction_logs')
    op.drop_index(op.f('ix_ai_interaction_logs_id'), table_name='ai_interaction_logs')
    op.drop_table('ai_interaction_logs')
    # ### end Alembic commands ###